export const dummyItems = [
    {
      id: 1,
      category: 'men',
      type: 'hoodie',
      name: 'Men\'s Classic Hoodie',
      price: 49.99,
      description: 'A comfortable and stylish hoodie for men.',
      imageUrl: '/../public/images/backpack.png',
    },
    {
      id: 2,
      category: 'men',
      type: 'jeans',
      name: 'Men\'s Sporty Hoodie',
      price: 59.99,
      description: 'A sporty hoodie designed for active men.',
      imageUrl: '/../public/images/backpack.png',
    },
    // Add more dummy items as needed
    {
      id: 3,
      category: 'men',
      type: 'T-shirt',
      name: 'Men\'s Basic T-shirt',
      price: 19.99,
      description: 'A simple and comfortable t-shirt for men.',
      imageUrl: '/../public/images/backpack.png',
    },
    // More items for the 'Man' category and other categories
    {
      id: 4,
      category: 'kids',
      type: 'Hoodie',
      name: 'Kids',
      price: 54.99,
      description: 'A cozy and warm hoodie for kids.',
      imageUrl: '/../public/images/boots.jpg',
    },
    {
      id: 5,
      category: 'sport',
      type: 'Hoodie',
      name: 'seport Cozy Hoodie',
      price: 54.99,
      description: 'A cozy and warm hoodie for sport.',
      imageUrl: '/images/womens-cozy-hoodie.jpg',
    },
    {
      id: 6,
      category: 'women',
      type: 'Hoodie',
      name: 'Women\'s Cozy Hoodie - women',
      price: 54.99,
      description: 'A cozy and warm hoodie for women.',
      imageUrl: '/../public/images/backpack.png',
    },
  ];